query FetchProductsByIds($where: String!, $limit: Int!) {
  products(where: $where, limit: $limit) {
    results {
      id
      masterData {
        current {
          nameAllLocales {
            locale
            value
          }
          masterVariant {
            id
            sku
            images {
              url
            }
            prices {
              value {
                centAmount
                currencyCode
                fractionDigits
              }
            }
          }
          variants {
            id
            sku
            images {
              url
            }
            prices {
              value {
                centAmount
                currencyCode
                fractionDigits
              }
            }
          }
        }
      }
    }
  }
}
